/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.rampage_v2.Ventanas;

import com.mycompany.rampage_v2.Juego.Jugador;
import com.mycompany.rampage_v2.Juego.Mapas.Mapa;
import com.mycompany.rampage_v2.Juego.Mapas.Mapa4x4;
import com.mycompany.rampage_v2.Juego.Mapas.Mapa6x4;
import com.mycompany.rampage_v2.Juego.Mapas.Mapa8x9;
import com.mycompany.rampage_v2.Juego.Vehiculos.Avion;
import com.mycompany.rampage_v2.Juego.Vehiculos.Vehiculo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author marito
 */
public class VisualJugador extends javax.swing.JFrame {

    /**
     * Creates new form VisualJugador
     */
    private Inicio inicio;
    private Jugador jugador;
    private final VisualJuego JUEGO;

    public VisualJugador(Inicio inicio) {
        JUEGO = new VisualJuego(inicio);
        initComponents();
        //iniciarComponentes();
        this.inicio = inicio;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();
        btnjugar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        spnlVehiculos = new javax.swing.JScrollPane();
        pnlVehiculos = new javax.swing.JPanel();
        spnlArmas = new javax.swing.JScrollPane();
        pnlArmas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(1000, 800));

        btnjugar.setFont(new java.awt.Font("DejaVu Serif Condensed", 2, 18)); // NOI18N
        btnjugar.setForeground(new java.awt.Color(0, 153, 153));
        btnjugar.setText("J        U        G        A        R");
        btnjugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjugarMouseClicked(evt);
            }
        });
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        lblInfo.setBackground(new java.awt.Color(0, 204, 153));

        btnSalir.setFont(new java.awt.Font("DejaVu Serif Condensed", 2, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 153));
        btnSalir.setText("S A L I R");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addComponent(btnjugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnjugar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );

        pnlVehiculos.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout pnlVehiculosLayout = new javax.swing.GroupLayout(pnlVehiculos);
        pnlVehiculos.setLayout(pnlVehiculosLayout);
        pnlVehiculosLayout.setHorizontalGroup(
            pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        pnlVehiculosLayout.setVerticalGroup(
            pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        spnlVehiculos.setViewportView(pnlVehiculos);

        pnlArmas.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlArmasLayout = new javax.swing.GroupLayout(pnlArmas);
        pnlArmas.setLayout(pnlArmasLayout);
        pnlArmasLayout.setHorizontalGroup(
            pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        pnlArmasLayout.setVerticalGroup(
            pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        spnlArmas.setViewportView(pnlArmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnlArmas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnlVehiculos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnlVehiculos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnlArmas)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JDialog dialogo;
    private int mapa;
    private void btnjugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjugarMouseClicked
        // TODO add your handling code here:
        dialogo = new JDialog(this, true);
        dialogo.setSize(350, 100);
        dialogo.setResizable(false);
        dialogo.setLayout(null);
        dialogo.setLocationRelativeTo(this);
        JLabel[] mapas = new JLabel[3];
        for (int i = 0; i < mapas.length; i++) {
            mapas[i] = new JLabel();
            dialogo.add(mapas[i]);
            mapas[i].setBounds((110 * i) + 10, 10, 100, 60);
            mapas[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    btnsmapasMouseClicked(evt);
                }

                private void btnsmapasMouseClicked(MouseEvent evt) {
                    Mapa mapa;
                    if (evt.getSource() == mapas[0]) {
                        mapa = new Mapa4x4();
                        JUEGO.setVehiculos(jugador.getVehiculos());
                        JUEGO.setMapa(mapa);
                    } else if (evt.getSource() == mapas[1]) {
                        mapa = new Mapa6x4();
                        JUEGO.setVehiculos(jugador.getVehiculos());
                        JUEGO.setMapa(mapa);
                    } else {
                        mapa = new Mapa8x9();
                        JUEGO.setVehiculos(jugador.getVehiculos());
                        JUEGO.setMapa(mapa);
                    }
                    setVisible(false);
                    JUEGO.setVisible(true);
                }
            });
        }
        mapas[0].setText("MAPA 4*4");
        mapas[1].setText("MAPA 6*4");
        mapas[2].setText("Mapa 9*8");
        dialogo.setVisible(true);
        //this.setVisible(false);
        //JUEGO.setVisible(true);
        //JUEGO.setMapa(new Mapa6x4());
    }//GEN-LAST:event_btnjugarMouseClicked

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnjugarActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnSalirMouseClicked

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

    public void iniciarPnlVehiculos() {
        pnlVehiculos.setPreferredSize(new Dimension(spnlVehiculos.getWidth()-10, jugador.getVehiculos().getContador()*80));
        JLabel[] vehiculos = new JLabel[jugador.getVehiculos().getContador()];
        pnlVehiculos.removeAll();
        for (int i = 0; i < jugador.getVehiculos().getContador(); i++) {
            Vehiculo referencia = jugador.getVehiculos().devolver(i + 1);
            referencia.getMuestra().setBounds(10, (60*i) + 10, pnlVehiculos.getWidth() - 20, 60);
            referencia.iniciarMuestra();
            vehiculos[i] = referencia.getMuestra();
            pnlVehiculos.add(vehiculos[i]);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnjugar;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JPanel pnlArmas;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlVehiculos;
    private javax.swing.JScrollPane spnlArmas;
    private javax.swing.JScrollPane spnlVehiculos;
    // End of variables declaration//GEN-END:variables

    public void iniciarComponentes() {
        lblInfo.setOpaque(false);
        lblInfo.setText("Nombre: " + jugador.getNombre() +
                "\n Nivel: " + jugador.getNivel() +
                "\n Experiencia: " + jugador.getExperiencia());
        verificarExperiencia();
    }

    private void verificarExperiencia() {
        JLabel[] experiencia = new JLabel[10];
        if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.1){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.2){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.3){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.4){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.5){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.6){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.7){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.8){  
        }else if(jugador.getExperiencia()/jugador.getExperienciaTope() < 0.9){  
        }
    }
}
